CREATE TABLE User (
  USER_ID VARCHAR(250) PRIMARY KEY,
  password VARCHAR(250) NOT NULL, 
  role VARCHAR(250) DEFAULT NULL
  
);

CREATE SEQUENCE USER_DETAIL_SEQ START WITH 0 INCREMENT BY 1 MAXVALUE 99999999999;

CREATE TABLE User_Detail (
  USER_DETAIL_ID INT DEFAULT USER_DETAIL_SEQ.NEXTVAL PRIMARY KEY,
  USER_ID VARCHAR(250) NOT NULL,
  fname VARCHAR(250) NOT NULL,
  lname VARCHAR(250) NOT NULL,
  addressl1 VARCHAR(250) DEFAULT NULL,
  addressl2 VARCHAR(250) DEFAULT NULL,
  city VARCHAR(250) DEFAULT NULL,
  state VARCHAR(250) DEFAULT NULL,
  zip INT DEFAULT NULL,
  contact BIGINT DEFAULT NULL  ,
  email VARCHAR(250) NOT NULL,
  foreign key (USER_ID) references User(USER_ID)
);

CREATE SEQUENCE ORDER_SEQ START WITH 0 INCREMENT BY 1 MAXVALUE 99999999999;

CREATE TABLE ORDERS (
  ORDER_ID INT DEFAULT ORDER_SEQ.NEXTVAL PRIMARY KEY,
  user_id VARCHAR(250) NOT NULL,
  order_date TIMESTAMP,
  status VARCHAR(250) DEFAULT NULL,
  total_amount DOUBLE NOT NULL,
  tax DOUBLE NOT NULL
);

CREATE SEQUENCE PRODUCT_SEQ START WITH 0 INCREMENT BY 1 MAXVALUE 99999999999;

CREATE TABLE PRODUCT (
  PRODUCT_ID INT DEFAULT PRODUCT_SEQ.NEXTVAL PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  company VARCHAR(250) NOT NULL,
  price DOUBLE DEFAULT NULL,
  quantity INT DEFAULT NULL
);

CREATE SEQUENCE ORDER_DETAIL_SEQ START WITH 0 INCREMENT BY 1 MAXVALUE 99999999999;

CREATE TABLE ORDER_DETAIL (
  ORDER_DETAIL_ID INT DEFAULT ORDER_DETAIL_SEQ.NEXTVAL PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  amount DOUBLE NOT NULL,
  foreign key (order_id) references ORDERS(ORDER_ID)
);
